import React from 'react'

export default function Series() {
    return (
        <div>
         <p>asdasdasd</p>
         <p>asdasdasd</p>
         <p>asdasdasd</p>
         <p>asdasdasd</p>
         <p>asdasdasd</p>
         <p>asdasdasd</p>
         <p>asdasdasd</p>
         <p>asdasdasd</p>
         <p>asdasdasd</p>
         <p>asdasdasd</p>
         <p>asdasdasd</p>
         <p>asdasdasd</p>
         <p>asdasdasd</p>
         <p>asdasdasd</p>
         <p>asdasdasd</p>
         <p>asdasdasd</p>
         <p>asdasdasd</p>
         <p>asdasdasd</p>
         <p>asdasdasd</p>
         <p>asdasdasd</p>
         <p>asdasdasd</p>
         <p>asdasdasd</p>
         <p>asdasdasd</p>
         <p>asdasdasd</p>
         <p>asdasdasd</p>
         <p>asdasdasd</p>
         <p>asdasdasd</p>
         <p>asdasdasd</p>
         <p>asdasdasd</p>
         <p>asdasdasd</p>
         <p>asdasdasd</p>
         <p>asdasdasd</p>
         <p>asdasdasd</p>
         <p>asdasdasd</p>
         <p>asdasdasd</p>
         <p>asdasdasd</p>
         <p>asdasdasd</p>
         <p>asdasdasd</p>
         <p>asdasdasd</p>
         <p>asdasdasd</p>
         <p>asdasdasd</p>
         <p>asdasdasd</p>
         <p>asdasdasd</p>
         <p>asdasdasd</p>
         <p>asdasdasd</p>
         <p>asdasdasd</p>
         <p>asdasdasd</p>
        </div>
    )
}
